[build-system]
requires = ["setuptools>=45"]
build-backend = "setuptools.build_meta"

[project]
name = "collection-task"
version = "0.1.0"
dependencies = []

[tool.setuptools.packages.find]
where = ["src"]
